apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-vrrrqotn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/java-quarkus-vrrrqotn:46bacd0897e62ca47278284fb0823b562fa70790@sha256:ad29cda0fcecfd2e73689de77ad0213e8d89204b660fdcce405008f3ae6f1418
          name: container-image
